fix: Make ConsoleLoggingHandler singleton class
atsign-foundation/at_tools pull request #227
Opened 2022-08-27 03:57 UTC by kalluriramkumar

**- What I did**
- The instances of ConsoleLoggingHandler are proportionate to the instances of AtSignLogger. Since ConsoleLoggingHandler is a state-less class, to optimise the memory usage, refactored to a singleton class.

**- How I did it**
- Add singleton nature to ConsoleLoggingHandler
- Add a static variable to hold ConsoleLoggingHandler in AtSignLogger.

**- How to verify it**
- The instances of ConsoleLoggingHandler should be only one. and logging mechanism should still work as earlier.

**- Description for the changelog**
- Optimise the memory usage.

2022-08-29 12:06 UTC, gkc requested changes

2022-08-29 12:06 UTC, gkc commented on at_utils/lib/src/logging/handlers.dart
> +  static final ConsoleLoggingHandler _singleton =
Doesn't need to be a forced singleton. Can just be a normal class. The change you've made to have a static instance in atsignlogger.dart is sufficient

2022-08-29 14:40 UTC, sitaram-kalluri commented on at_utils/lib/src/logging/handlers.dart
> +  static final ConsoleLoggingHandler _singleton =
Reverted the singleton nature of ConsoleLoggingHandler class.

2022-08-30 12:22 UTC, gkc approved these changes

2022-08-30 12:22 UTC, merged