feat: `sshnp_register_tool/`
atsign-foundation/at_tools pull request #237
Opened 2022-09-30 00:23 UTC by JeremyTubongbanua

# What I did

Create a register tool for [sshnp](https://github.com/atsign-foundation/sshnoports). Easily get and onboard atSigns for the client and device and also easily create the sshnpd.service to later edit via `sudo nano`.

Wrote [README.md](https://github.com/JeremyTubongbanua/at_tools/blob/trunk/sshnp_register_tool/README.md) instructions

2022-10-05 23:52 UTC, JeremyTubongbanua commented
Just need to test on Windows & Linux, then will open this PR.

2022-10-07 08:34 UTC, cpswan commented on sshnp_register_tool/README.md
> +## 2. Binary
Can we create binaries (using a GitHub Action) and make them available here as releases?

2022-10-07 08:37 UTC, cpswan commented on sshnp_register_tool/README.md
> +1. example of onboarding a free new atSign
Each of the examples is quite long, and would benefit from using the details tag - https://gist.github.com/scmx/eca72d44afee0113ceb0349dd54a84a2

2022-10-07 08:44 UTC, cpswan requested changes
Great work @JeremyTubongbanua 

One of my asks is trivial, and is a quick fix before merging. The other is more of a heavy lift, and I'm happy for it to be turned into issues for future work.

2022-10-07 08:44 UTC, cpswan commented on sshnp_register_tool/bin/sshnp_register_tool.dart
> +/// This binary should realistically be only ran once to initialize and register the device's atSign.
s/ran/run/

2022-10-07 08:44 UTC, cpswan commented on sshnp_register_tool/pubspec.yaml
> +dependencies:
Please add a dependabot config to keep these up to date. There should also be tests to ensure that everything still works when a dependency is bumped, and when those tests pass we can build and release binaries.

2022-10-14 05:52 UTC, cconstab reviewed
As this in its current format is specific to sshnoports perhaps it belongs in that repo.

I had imagined a standalone tool useful for anything.

Again perhaps that is a better thing to do here and have the sshnoports extensions in the sshnp repo..

Very cool in either case ty!

2023-03-08 18:36 UTC, gkc commented
@JeremyTubongbanua Please can you spend a little time to address the comments in this PR?

2023-03-16 16:26 UTC, JeremyTubongbanua commented
Hi, sorry, I will try to get on this next week when my capacity is larger.

2023-06-10 14:08 UTC, cconstab commented
Still open!

2023-06-11 15:04 UTC, closed without merging