feat: add isLocal to verb builders
atsign-foundation/at_tools pull request #242
Opened 2022-10-16 03:19 UTC by kalluriramkumar

**- What I did**
- Add isLocal to UpdateVerbBuilder and local_lookup_verb builder

**- How I did it**

**- How to verify it**

**- Description for the changelog**
- Add isLocal to verb builder

2022-10-16 15:51 UTC, gkc requested changes
LGTM, one request

2022-10-16 15:51 UTC, gkc commented on at_commons/lib/src/verb/update_verb_builder.dart
>        command += 'public:';
We need to make sure there are guard conditions which prevent local keys also being public. A local key **must not** be (1) public (2) shared with anyone else. Likewise, a key that is public, or shared with someone else, **must not** be local

2022-10-19 06:07 UTC, murali-shris commented on at_commons/lib/src/verb/llookup_verb_builder.dart
> +    if(isLocal){
dart format missing

2022-10-19 08:48 UTC, murali-shris approved these changes

2022-10-19 10:45 UTC, gkc approved these changes
LGTM for now. Could do with adding more validation of mutual exclusivity in the AtKey setters

2022-10-19 10:47 UTC, merged