refactor: deprecate formatAtsign() and move logic to fixAtsign()
atsign-foundation/at_tools pull request #300
Opened 2023-03-14 08:37 UTC by srieteja

closes https://github.com/atsign-foundation/at_tools/issues/293
**- What I did**
- deprecate formatAtsign()
- move its functionality to fixAtSign()
- fixAtSign() does not throw an exception anymore when an atsign without '@' is input
- updated tests to match current behaviour
- Tests previously assumed that atkey would be passed as input to fixAtSign() which is not accurate. Updated tests to assert/expect atsigns and verify the behaviour

**- How to verify it**
- New test case added and older tests modified in test/fix_atsign_test.dart

**- Description for the changelog**

refactor: deprecate formatAtsign() and move logic to fixAtsign()

2023-03-14 14:00 UTC, murali-shris requested changes

2023-03-14 14:00 UTC, murali-shris commented on packages/at_utils/lib/src/atsign_util.dart
> +  @Deprecated('Use formatAtSign()')
should be 'Use fixAtSign'

2023-03-14 14:20 UTC, srieteja commented on packages/at_utils/lib/src/atsign_util.dart
> +  @Deprecated('Use formatAtSign()')
Changed as part of https://github.com/atsign-foundation/at_tools/pull/300/commits/69858083545c4408f217dc6e39b7ee6bf9e2fba9

2023-03-15 09:40 UTC, murali-shris approved these changes, later dismissed

2023-03-15 15:32 UTC, murali-shris submitted a review, later dismissed

2023-03-15 15:42 UTC, murali-shris approved these changes

2023-03-15 15:42 UTC, merged